### PR TITLE
Migrate to GitHub Actions

### PR DESCRIPTION
**Pull request by DanielRuf**
Let's try GitHub Actions which is often faster and more flexible.

### CODE REVIEW

**Comment by Zulko** [comment]
Interesting. How to know if for instance this PR tests correctly. Is it going to be processed by Github Actions?

**Comment by DanielRuf** [comment]
It is only processed if it is merged or on another branch. I will push the branch to the upstream so we can directly see it.

**Comment by Zulko** [comment]
Sounds good thanks. Curious to see how it works!

**Comment by DanielRuf** [comment]
Hey, @Zulko, did you already signup for the GHA beta? =)

**Comment by DanielRuf** [comment]
Current status: https://github.com/danielruf/ReLaXed/commit/f0ef782a074e00f57698e50fc909fe451e0399b0/checks?check_suite_id=272812738

**Pull request closed without merging**
