### PR TITLE
Add option to build document one time

### PR DESCRIPTION
**Pull request by tht13**
Adds a command line option to build the workspace once rather than watch.

I know from other fork requests you don't like this idea, but I would really like to use your library in CI/CD so having a watching script simply doesn't work.

### CODE REVIEW

**Comment by DanielRuf** [comment]
Hi, thanks for your proposal and congrats to your first PR for ReLaXed 🎉 =)
This looks good. What do you think @Zulko?

**Comment by Zulko** [comment]
- @tht13 have you tested it extensively and in particular do you experience the same problem as in #44 (page printed before the rendering is finished)
- I'm not sure ``--build`` is the best term, maybe ``--once`` would be better ?
- We can do some more refactoring later, but I don't like that the watching loop is now 3 indentations deep. Can we put the watching loop into some function, so that the main process will look as simple as

```
if --once {
  convert()
} else {
  watch()
}
```

@tht13 what is your intended use in CI ?

**Comment by tht13** [comment]
- @Zulko I have not seen the problem from #44 arise, but I will run it against all the examples to check.
- I will change the argument, `--once` is better
- I can refactor this too
- I am using this in CI to auto generate user documentation such as README, Installation Guide (they have specific marketing styling requirements, which is why your package seems promising)

@benperiton I did originally extract the code into a `convert` function which both methods called, however it seems the change event only rebuilds the latest file to change, as a single build needs to target the main file to generate the pdf the rest of the code seemed unnecessary then. 
I was concerned about skipping charts, but without scrapping the folders in `watchedLocations` for all files which match a build extension there is no way to include them. 
Maybe this is the cause of #44, that if the user had not edited the `*.chart.js* file (or other) that the `*.png` file will not have been created and thus not included in the output pdf.

**Comment by tht13** [comment]
After testing I found I have to use the arg `--build-once` as the arg `--once` caused issues with commander, as commander extends `Node.EventEmmiter` which already has a `once` property. 

I also ran the following script to check for accuracy,

```bash
#! /bin/bash
SCRIPT=`realpath $1`
EXAMPLES=$2

cd $EXAMPLES

cd examples
for FILE in `ls -1`
do 
echo "Building example $FILE"
cd $FILE
$SCRIPT --build-once ./$FILE.pug
rm ${FILE}_temp.htm
cd ..
done
cd ..
git status
```

run with `once.sh ./src/index.js ../ReLaxed-examples`

Git status returned differences with what appeared to be word wrappings (ie a trailing line in book.pdf ended up on the next page), but visually the documents were the same. I wonder if this is up to the OS chrome is running on, or maybe a newer version of chrome is being used.

With regards to #44, I found that the build command did have to be run twice to get a useful output.

**Comment by Zulko** [comment]
Thanks very much. Looks good to me. Will wait a bit for comments and merge soon. Im not sure what you mean by 'the command needs to be run twice to get useful output'. Which command ia that ? The one with build once ?

**Comment by tht13** [comment]
I mean the function `masterFileToPDF` must be called twice. If its only called once some of the examples produce blank pdf's.
https://github.com/RelaxedJS/ReLaXed/pull/46/files#diff-1fdf421c05c1140f6d71444ea2b27638R93

**Comment by Zulko** [comment]
Just a note that I will merge this just after I merge my own branch. I believe I have solved the problem of "garbled" pdfs on first call, I have cut the PDF generation time at least 2-fold for most cases, I have solved a few bugs and made some new features work. Look out for the next version :)

**Pull request merged**
