### PR TITLE
changed main file in package.json from index.js to masterToPDF.js

### PR DESCRIPTION
**Pull request by mayank**
to export the package as a module

To use this as a `node_module` this should be the main file.

### CODE REVIEW

**Comment by Zulko** [comment]
That sounds correct. Are you using Relaxed as a node module?

**Comment by mayank** [comment]
Yes, creating a server to that will be able to convert templates into pdf.

**Comment by mayank** [comment]
please merge this if possible!

**Comment by mayank** [comment]
@DanielRuf updated the comment!

**Comment by mayank** [comment]
@DanielRuf any expected time this will get merged?

**Comment by DanielRuf** [comment]
Release planning and merging is handled by @Zulko.

**Comment by DanielRuf** [comment]
Would be helpful to write some docs for NodeJS users. Can you add some @mayank in the readme?

**Comment by mayank** [comment]
> Would be helpful to write some docs for NodeJS users. Can you add some @mayank in the readme?

sure!

**Comment by mayank** [comment]
> Would be helpful to write some docs for NodeJS users. Can you add some @mayank in the readme?

Added the documentation.

**Pull request merged**
