### PR TITLE
Feat: --locals support json files; Test: Add tests for --locals arg

### PR DESCRIPTION
**Pull request by hinok**
Hey,
I've wanted to read json from a static file because using the current cli option `--locals` is a bit hard with big, inlined json.

**This PR:**

- Add support for loading json files by using `--locals ./data.json`
- Handle watching changes of the file defined in `--locals` (e.g. `./data.json`)
- Use the current implementation of `ReLaXed` in tests instead of globally installed `relaxedjs`
- Add two new tests that cover usage of `--locals` with
  - inline json `--locals { "name": "Foo" }`
  - json file `--locals ./data.json`

I'd like also to update `README.md` or maybe Wiki (?) because I've spent good amount of time figuring out why tests had been failing all the time.

The problem was that I haven't had installed dependencies of [`pdf-image`](https://www.npmjs.com/package/pdf-image), after installing `ghostscript` and `poppler`, tests work and pass.

### CODE REVIEW

**Comment by mayank** [comment]
@hinok can you please add watcher to the json file updates.

**Comment by hinok** [comment]
@mayank Added handling changes of a json file passed through `--locals`.

**Comment by hinok** [comment]
@DanielRuf @Zulko Could you look at this PR? If you want, I can `squash` commits.

**Comment by DanielRuf** [comment]
Hi @hinok,

thanks for the PR an proviing tests 🙇 

I will try to invest some time next week to review your changes.

**Comment by DanielRuf** [comment]
Hi @hinok,

thanks for the PR an providing tests 🙇 

I will try to invest some time next week to review your changes.

@Zulko what o you think about the proposed changes?

**Comment by hinok** [comment]
@DanielRuf @Zulko Any updates?

**Comment by ObserverOfTime** [comment]
Please merge this PR soon, this feature is very useful.

**Comment by hinok** [comment]
thanks @Zulko 🎉

**Pull request merged**
