### PR TITLE
Correctly set sandbox mode depending on provided --no-sandbox argumen…

### LINKED ISSUE #127: --no-sandbox does not work
When i run

`./node_modules/.bin/relaxed temp/my.pug --build-once`

then I can see these logs

```
--- puppeteerConfig= { headless: true,
  args:
   [ '--no-sandbox',
     '--disable-translate',
     '--disable-extensions',
     '--disable-sync' ] }
```

In another case when I run next line

`./node_modules/.bin/relaxed temp/my.pug --no-sandbox --build-once`

then I can see next logs

```
--- puppeteerConfig= { headless: true,
  args:
   [ '--disable-translate',
     '--disable-extensions',
     '--disable-sync' ] }
```

Fix it please

### PR DESCRIPTION
**Pull request by DanielRuf**
…t, fixes #127

### CODE REVIEW

**Comment by DanielRuf** [comment]
@ifgeny87 you can also apply / test it with https://github.com/RelaxedJS/ReLaXed/pull/128#event-2294381900.patch or https://github.com/RelaxedJS/ReLaXed/pull/128#event-2294381900.diff if you want to apply it now before it is merged into master and a new release done.

**Comment by DanielRuf** [comment]
@ifgeny87 you can also apply / test it with https://github.com/RelaxedJS/ReLaXed/pull/128.patch or https://github.com/RelaxedJS/ReLaXed/pull/128.diff if you want to apply it now before it is merged into master and a new release done.

**Comment by Zulko** [comment]
:+1: Thanks @DanielRuf

**Comment by DanielRuf** [comment]
@Zulko can we merge this?

**Pull request merged**
