### PR TITLE
Add argument to disable puppeteer sandbox

### LINKED ISSUE #19: No option to run puppeteer without a sandbox
I'm envisioning grand plans of using ReLaXed to auto-build my documents after each commit using Travis, but #2 as well as the inability to run ReLaXed without sandboxing makes this impossible.

Relevant puppeteer documentation: https://github.com/GoogleChrome/puppeteer/blob/master/docs/troubleshooting.md#running-puppeteer-on-travis-ci

I'd love to contribute a PR if you're okay with this!

### PR DESCRIPTION
**Pull request by veggiedefender**
Fixes #19 (see issue for details + justification for this PR)

I also broke out the puppeteer configuration into a separate function to make it clear what the code is doing and to make it easier to extend the config logic in the future.

### CODE REVIEW

**Comment by Zulko** [comment]
I'm ok with this PR but it now has conflicts since I pushed the last PR. I'll have a look a bit later, unless you want to resolve the conflict yourself ?

**Comment by veggiedefender** [comment]
I think that should do it

**Comment by Zulko** [comment]
Question: what is the advantage of defining a ``configurePuppeteer()`` function here ? (instead of simply directly the configuration, as a constant)

**Comment by veggiedefender** [comment]
It just feels a little weird to me to shove too much logic into `main()`, and putting it in a function both separates the code and gives it a name.

If you want, I can change it so it's like

```js
console.log('Watching ' + input + ' and its directory tree.')
const config = {
  headless: true
}
if (!program.sandbox) {
  config.args = ['--no-sandbox']
}
const browser = await puppeteer.launch()
const page = await browser.newPage()
```

but to me that isn't as nice. It's up to you though.

**Pull request merged**
