### PR TITLE
Configuration

### PR DESCRIPTION
**Pull request by Drew-S**
-   Commenting on every file
-   Formatting fixes (readability)
-   Spacing fixes (readability) (2 -> 4 space indent)
-   Naming convention changes (index.js) (Needs review most)
-   Disabled code (index.js) proposal on loading per pdf config, global user config, global user templates, etc.
-   Change temp directory from current working / provided to OS temp directory (linux: /tmp/relaxed-######)

### CODE REVIEW

**Comment by Zulko** [comment]
I believe we should discuss the features before you implement them. For instance I disagree with the temp directory, the fact that the final page is in the same directory is very helpful for troubleshooting. The space changing is also a matter of preference (but less of a problem). Other than this it is pretty brilliant but I wouldn't spend too much time optimizing the structure given how 80% of it may end up in plugins.

**Comment by Zulko** [comment]
If you revert the default temp directory thing it is a green light for me.

**Comment by Drew-S** [comment]
Right now the temp HTML is a good debug tool, but for the end user its mostly useless. I think we could use the os temp, but add a flag to the program `--html` to output the final html to the working directory.

But, currently the HTML file is created after pug is finished rendering and my bibliography manipulates the dom in page, after this. So currently the HTML does not include that generated content. I am not sure if debugging the HTML file immediately after the pug is where it is needed more or if we should save the HTML from the page once its finished generating the bibliography?

**Comment by Zulko** [comment]
By troubleshooting, I meant user-side troubleshooting of the user's document, not us troubleshooting ReLaXed. Another use is that it can be easier to watch the HTML rather than the PDF when you are editing documents, because the HTML is ready faster than the PDF.

**Comment by Drew-S** [comment]
Right, did not really think of it as trouble shooting for the user, I will remove the os temp directory and should I change the HTML output to be from page? So that the bibliography will show up, as currently it does not in the HTML file.

**Comment by Zulko** [comment]
I'd say only if it doesnt add too much to the overall computing time.

**Comment by Drew-S** [comment]
I seem to be having some odd issues with the tests. Travis is clearly showing this is failing here, I get the same failure on my local machine. But the odd thing is, the master branch (both here and in my forked repo) pass in Travis, but the master's fails on my local machine. By all accounts I cannot see why, when I run relaxed directly I do not encounter any issues, everything renders and runs correctly.

**Comment by Zulko** [comment]
if you don't uncomment this line, the temporary html never gets written:

https://github.com/Drew-S/ReLaXed/blob/6c1f1feddca93a519d2f637636c5b002f025c2b2/src/converters.js#L243

please uncomment this line.

Btw another reason why the temp HTML cannot be in a temporary folder is because it would break all the links to the assets (at least as the code is, there may be a way to simply pass the html to the puppeteer page and tell puppeteer which dir to watch, but there is no reason to go there at the moment).

**Comment by Zulko** [comment]
@Drew-S just a note that

1. I reverted the coding style back to mine (2-space indent etc.), I'll try to enforce it with some config file in the future (im not sure how, some kind of eslint.config)

2. I'm adding a bit more tests and fixing the existing one, notably by cleaning rendered files inbetween tests.

**Comment by Drew-S** [comment]
That's fine, I can upload my eslint to my new updates after changing it to 2 space. I also started to work on improving unit tests [Tests](https://github.com/Drew-S/ReLaXed/tree/Tests). My new tests are performing correctly on my local machine, though they are failing in travis.

**Comment by Zulko** [comment]
Same problem here with travis, i believe it is just slow. Dont be too thorough with tests, since most of them may have to be migrated when the converters become plugins

**Pull request merged**
